// react/src/components/AppHeader.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useLocale } from "@/hooks/useLocale";
import LangSelect from "./LangSelect";
export default function AppHeader() {
    const { t } = useLocale();
    return (_jsxs("header", { className: "app-header flex-between", children: [_jsxs("h1", { children: [t("app.title"), _jsx("span", { className: "framework-badge", children: "React" })] }), _jsx(LangSelect, {})] }));
}

// vue/src/components/AppHeader.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";
import LangSelect from "@/components/LangSelect.vue";

const { t } = useLocale();
</script>

<template>
  <header class="app-header flex-between">
    <h1>
      {{ t("app.title") }}
      <span class="framework-badge">Vue</span>
    </h1>
    <LangSelect />
  </header>
</template>
