// react/src/components/CustomSelect.tsx
import { useState, useEffect, useRef } from "react";

export interface Option {
  value: string;
  label: string;
}

interface Props {
  value: string;
  options: Option[];
  renderTrigger: (option: Option | undefined) => React.ReactNode;
  renderOption: (option: Option) => React.ReactNode;
  onChange: (value: string) => void;
  className?: string;
}

export default function CustomSelect({ value, options, renderTrigger, renderOption, onChange, className }: Props) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function onOutside(e: MouseEvent) {
      if (!ref.current?.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onOutside);
    return () => document.removeEventListener("mousedown", onOutside);
  }, []);

  function select(val: string) {
    onChange(val);
    setOpen(false);
  }

  const selected = options.find(o => o.value === value);

  return (
    <div className={`custom-select${className ? ` ${className}` : ""}`} ref={ref}>
      <button type="button" className="custom-select-trigger" onClick={() => setOpen(o => !o)}>
        {renderTrigger(selected)}
      </button>
      {open && (
        <div className="custom-select-dropdown">
          {options.map(opt => (
            <button
              key={opt.value}
              type="button"
              className={`custom-select-option${opt.value === value ? " is-selected" : ""}`}
              onClick={() => select(opt.value)}
            >
              {renderOption(opt)}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// vue/src/components/CustomSelect.vue
<script setup lang="ts" generic="T extends string">
import { ref, onMounted, onUnmounted } from "vue";

const props = defineProps<{
  modelValue: T;
  options: { value: T; label: string }[];
}>();

const emit = defineEmits<{ "update:modelValue": [value: T] }>();

const open = ref(false);
const container = ref<HTMLElement>();

function onOutside(e: MouseEvent) {
  if (!container.value?.contains(e.target as Node)) open.value = false;
}
onMounted(() => document.addEventListener("mousedown", onOutside));
onUnmounted(() => document.removeEventListener("mousedown", onOutside));

function select(value: T) {
  emit("update:modelValue", value);
  open.value = false;
}
</script>

<template>
  <div class="custom-select" ref="container">
    <button type="button" class="custom-select-trigger" @click="open = !open">
      <slot name="trigger" :option="options.find(o => o.value === modelValue)" />
    </button>

    <div v-if="open" class="custom-select-dropdown">
      <button
        v-for="opt in options"
        :key="opt.value"
        type="button"
        class="custom-select-option"
        :class="{ 'is-selected': opt.value === modelValue }"
        @click="select(opt.value)"
      >
        <slot name="option" :option="opt" />
      </button>
    </div>
  </div>
</template>
