// react/src/components/LangSelect.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useLocale } from "@/hooks/useLocale";
import CustomSelect from "./CustomSelect";
export default function LangSelect() {
    const { locale, localeOptions, setLocale } = useLocale();
    const options = localeOptions.map(o => ({ value: o.code, label: `${o.flag} ${o.label}` }));
    return (_jsx(CustomSelect, { value: locale, options: options, className: "lang-select", renderTrigger: opt => opt?.label ?? "", renderOption: opt => opt?.label ?? "", onChange: val => setLocale(val) }));
}

// vue/src/components/LangSelect.vue
<script setup lang="ts">
import { computed } from "vue";
import { useLocale } from "@/composables/useLocale";
import type { Locale } from "@common/i18n/locale";
import CustomSelect from "./CustomSelect.vue";

const { locale, localeOptions, setLocale } = useLocale();

const mapped = computed(() =>
  localeOptions.value.map(o => ({ value: o.code, label: `${o.flag} ${o.label}` }))
);
</script>

<template>
  <CustomSelect
    :modelValue="locale"
    :options="mapped"
    class="lang-select"
    @update:modelValue="setLocale($event as Locale)"
  >
    <template #trigger="{ option }">{{ option?.label }}</template>
    <template #option="{ option }">{{ option.label }}</template>
  </CustomSelect>
</template>
