// react/src/components/SearchFilter.tsx
import { useCallback } from "react";
import { useLocale } from "@/hooks/useLocale";
import { tripStatusFilterOptions as statusOptions } from "@common/models/tripStatusOptions";
import StatusSelect from "./StatusSelect";

interface Props {
  search: string;
  dateFrom: string;
  dateTo: string;
  status: string;
  onChange: (field: "search" | "dateFrom" | "dateTo" | "status", value: string) => void;
}

export default function SearchFilter({ search, dateFrom, dateTo, status, onChange }: Props) {
  const { t } = useLocale();
  const onSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => onChange("search", e.target.value), [onChange]);
  const onDateFrom = useCallback((e: React.ChangeEvent<HTMLInputElement>) => onChange("dateFrom", e.target.value), [onChange]);
  const onDateTo = useCallback((e: React.ChangeEvent<HTMLInputElement>) => onChange("dateTo", e.target.value), [onChange]);
  const onStatus = useCallback((v: string) => onChange("status", v), [onChange]);
  return (
    <div className="filters-bar">
      <div className="filter-group filter-search">
        <label className="filter-label">{t("trips.search")}</label>
        <input type="text" className="filter-input" placeholder={t("trips.search")} value={search} onChange={onSearch} />
      </div>
      <div className="filter-group">
        <label className="filter-label">{t("trips.dateFrom")}</label>
        <input type="date" className="filter-input" value={dateFrom} onChange={onDateFrom} />
      </div>
      <div className="filter-group">
        <label className="filter-label">{t("trips.dateTo")}</label>
        <input type="date" className="filter-input" value={dateTo} onChange={onDateTo} />
      </div>
      <div className="filter-group">
        <label className="filter-label">{t("table.status")}</label>
        <StatusSelect value={status} options={statusOptions} onChange={onStatus} />
      </div>
    </div>
  );
}

// vue/src/components/SearchFilter.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";
import { tripStatusFilterOptions as statusOptions } from "@common/models/tripStatusOptions";
import StatusSelect from "@/components/StatusSelect.vue";

const props = defineProps<{
  search: string;
  dateFrom: string;
  dateTo: string;
  status: string;
}>();

const emit = defineEmits<{
  "update:search": [value: string];
  "update:dateFrom": [value: string];
  "update:dateTo": [value: string];
  "update:status": [value: string];
}>();

const { t } = useLocale();
</script>

<template>
  <div class="filters-bar">
    <div class="filter-group filter-search">
      <label class="filter-label">{{ t("trips.search") }}</label>
      <input
        type="text"
        class="filter-input"
        :placeholder="t('trips.search')"
        :value="search"
        @input="emit('update:search', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="filter-group">
      <label class="filter-label">{{ t("trips.dateFrom") }}</label>
      <input
        type="date"
        class="filter-input"
        :value="dateFrom"
        @input="emit('update:dateFrom', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="filter-group">
      <label class="filter-label">{{ t("trips.dateTo") }}</label>
      <input
        type="date"
        class="filter-input"
        :value="dateTo"
        @input="emit('update:dateTo', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="filter-group">
      <label class="filter-label">{{ t("table.status") }}</label>
      <StatusSelect
        :modelValue="status"
        :options="statusOptions"
        @update:modelValue="emit('update:status', $event)"
      />
    </div>
  </div>
</template>
