// react/src/components/SearchFilter.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCallback } from "react";
import { useLocale } from "@/hooks/useLocale";
import { tripStatusFilterOptions as statusOptions } from "@common/models/tripStatusOptions";
import StatusSelect from "./StatusSelect";
export default function SearchFilter({ search, dateFrom, dateTo, status, onChange }) {
    const { t } = useLocale();
    const onSearch = useCallback((e) => onChange("search", e.target.value), [onChange]);
    const onDateFrom = useCallback((e) => onChange("dateFrom", e.target.value), [onChange]);
    const onDateTo = useCallback((e) => onChange("dateTo", e.target.value), [onChange]);
    const onStatus = useCallback((v) => onChange("status", v), [onChange]);
    return (_jsxs("div", { className: "filters-bar", children: [_jsxs("div", { className: "filter-group filter-search", children: [_jsx("label", { className: "filter-label", children: t("trips.search") }), _jsx("input", { type: "text", className: "filter-input", placeholder: t("trips.search"), value: search, onChange: onSearch })] }), _jsxs("div", { className: "filter-group", children: [_jsx("label", { className: "filter-label", children: t("trips.dateFrom") }), _jsx("input", { type: "date", className: "filter-input", value: dateFrom, onChange: onDateFrom })] }), _jsxs("div", { className: "filter-group", children: [_jsx("label", { className: "filter-label", children: t("trips.dateTo") }), _jsx("input", { type: "date", className: "filter-input", value: dateTo, onChange: onDateTo })] }), _jsxs("div", { className: "filter-group", children: [_jsx("label", { className: "filter-label", children: t("table.status") }), _jsx(StatusSelect, { value: status, options: statusOptions, onChange: onStatus })] })] }));
}

// vue/src/components/SearchFilter.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";
import { tripStatusFilterOptions as statusOptions } from "@common/models/tripStatusOptions";
import StatusSelect from "@/components/StatusSelect.vue";

const props = defineProps<{
  search: string;
  dateFrom: string;
  dateTo: string;
  status: string;
}>();

const emit = defineEmits<{
  "update:search": [value: string];
  "update:dateFrom": [value: string];
  "update:dateTo": [value: string];
  "update:status": [value: string];
}>();

const { t } = useLocale();
</script>

<template>
  <div class="filters-bar">
    <div class="filter-group filter-search">
      <label class="filter-label">{{ t("trips.search") }}</label>
      <input
        type="text"
        class="filter-input"
        :placeholder="t('trips.search')"
        :value="search"
        @input="emit('update:search', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="filter-group">
      <label class="filter-label">{{ t("trips.dateFrom") }}</label>
      <input
        type="date"
        class="filter-input"
        :value="dateFrom"
        @input="emit('update:dateFrom', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="filter-group">
      <label class="filter-label">{{ t("trips.dateTo") }}</label>
      <input
        type="date"
        class="filter-input"
        :value="dateTo"
        @input="emit('update:dateTo', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="filter-group">
      <label class="filter-label">{{ t("table.status") }}</label>
      <StatusSelect
        :modelValue="status"
        :options="statusOptions"
        @update:modelValue="emit('update:status', $event)"
      />
    </div>
  </div>
</template>
