// react/src/components/StatusSelect.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useLocale } from "@/hooks/useLocale";
import { tripStatusFilterOptions as statusOptions } from "@common/models/tripStatusOptions";
import CustomSelect from "./CustomSelect";
function badgeClass(value) {
    return value ? `badge-${value}` : "badge-select-all";
}
export default function StatusSelect({ value, options = statusOptions, onChange }) {
    const { t } = useLocale();
    const mapped = options.map(o => ({ value: o.value, label: t(o.label) }));
    return (_jsx(CustomSelect, { value: value, options: mapped, onChange: onChange, renderTrigger: opt => (_jsxs("span", { className: `badge status-select-trigger-badge ${badgeClass(opt?.value ?? "")}`, children: [opt?.label, " ", _jsx("span", { children: "\u25BE" })] })), renderOption: opt => (_jsx("span", { className: `badge status-select-option ${badgeClass(opt.value)}`, children: opt.label })) }));
}

// vue/src/components/StatusSelect.vue
<script setup lang="ts">
import { computed } from "vue";
import { useLocale } from "@/composables/useLocale";
import type { StatusOption } from "@common/models/tripStatusOptions";
import CustomSelect from "./CustomSelect.vue";

const props = defineProps<{
  modelValue: string;
  options: StatusOption[];
}>();

const emit = defineEmits<{ "update:modelValue": [value: string] }>();

const { t } = useLocale();

const mapped = computed(() =>
  props.options.map(o => ({ value: o.value, label: t(o.label) }))
);

function badgeClass(value: string) {
  return value && value !== "" ? `badge-${value}` : "badge-select-all";
}
</script>

<template>
  <CustomSelect
    :modelValue="modelValue"
    :options="mapped"
    @update:modelValue="emit('update:modelValue', $event)"
  >
    <template #trigger="{ option }">
      <span class="badge status-select-trigger-badge" :class="badgeClass(option?.value ?? '')">
        {{ option?.label }}
        <span class="status-select-chevron">▾</span>
      </span>
    </template>
    <template #option="{ option }">
      <span class="badge status-select-option" :class="badgeClass(option.value)">{{ option.label }}</span>
    </template>
  </CustomSelect>
</template>
