// angular/src/app/components/trip-table-skeleton.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslatePipe } from '../pipes/translate.pipe';

@Component({
  selector: 'app-trip-table-skeleton',
  standalone: true,
  imports: [CommonModule, TranslatePipe],
  template: `
    <div class="table-container">
      <table class="table">
        <thead>
          <tr>
            <th>{{ 'table.origin' | t }}</th>
            <th>{{ 'table.destination' | t }}</th>
            <th>{{ 'table.departure' | t }}</th>
            <th>{{ 'table.status' | t }}</th>
            <th>{{ 'table.duration' | t }}</th>
            <th>{{ 'table.actions' | t }}</th>
          </tr>
        </thead>
        <tbody>
          @for (i of rows; track i) {
            <tr>
              @for (j of cols; track j) {
                <td>
                  <div class="skeleton skeleton-text" [style.width.px]="j === 5 ? 120 : 100"></div>
                </td>
              }
            </tr>
          }
        </tbody>
      </table>
    </div>
  `
})
export class TripTableSkeletonComponent {
  protected readonly rows = [0, 1, 2, 3, 4];
  protected readonly cols = [0, 1, 2, 3, 4, 5];
}

// vue/src/components/TripTableSkeleton.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";

const { t } = useLocale();
</script>

<template>
  <div class="card">
    <table class="table">
      <thead>
        <tr>
          <th>{{ t("table.origin") }}</th>
          <th>{{ t("table.destination") }}</th>
          <th>{{ t("table.departure") }}</th>
          <th>{{ t("table.arrival") }}</th>
          <th>{{ t("table.status") }}</th>
          <th>{{ t("table.duration") }}</th>
          <th>{{ t("table.driver") }}</th>
          <th>{{ t("table.actions") }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="i in 5" :key="i">
          <td><div class="skeleton skeleton-text"></div></td>
          <td><div class="skeleton skeleton-text"></div></td>
          <td><div class="skeleton skeleton-text"></div></td>
          <td><div class="skeleton skeleton-text"></div></td>
          <td><div class="skeleton skeleton-badge"></div></td>
          <td><div class="skeleton skeleton-text-sm"></div></td>
          <td><div class="skeleton skeleton-text"></div></td>
          <td><div class="skeleton skeleton-actions"></div></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
