// vue/src/components/TripTable.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";
import { formatCompactDateTime, formatDuration, isNextDay } from "@common/utils/time";
import type { Trip } from "@common/models/trip";
import TripStatusBadge from "./TripStatusBadge.vue";

defineProps<{ trips: Trip[] }>();
defineEmits<{
  view: [id: number];
  edit: [id: number];
  cancel: [id: number];
}>();

const { t } = useLocale();
</script>

<template>
  <div class="card">
    <table class="table">
      <thead>
        <tr>
          <th>{{ t("table.origin") }}</th>
          <th>{{ t("table.destination") }}</th>
          <th>{{ t("table.departure") }}</th>
          <th>{{ t("table.arrival") }}</th>
          <th>{{ t("table.status") }}</th>
          <th>{{ t("table.duration") }}</th>
          <th>{{ t("table.driver") }}</th>
          <th>{{ t("table.actions") }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="trip in trips" :key="trip.id" class="table-row-clickable" @click="$emit('view', trip.id)">
          <td>{{ trip.origin }}</td>
          <td>{{ trip.destination }}</td>
          <td class="time-cell">{{ formatCompactDateTime(trip.departureTime, trip.departureTimezone) }}</td>
          <td class="time-cell">
            <template v-if="trip.arrivalTime">
              {{ formatCompactDateTime(trip.arrivalTime, trip.arrivalTimezone) }}
              <span v-if="isNextDay(trip.departureTime, trip.departureTimezone, trip.arrivalTime, trip.arrivalTimezone)" class="next-day">+1</span>
            </template>
            <span v-else class="text-secondary">—</span>
          </td>
          <td><TripStatusBadge :status="trip.status" /></td>
          <td class="text-secondary">
            <span v-if="trip.arrivalTime">{{ formatDuration(trip.departureTime, trip.arrivalTime) }}</span>
            <span v-else>—</span>
          </td>
          <td>{{ trip.driver }}</td>
          <td>
            <div class="actions">
              <button class="btn btn-sm" @click.stop="$emit('view', trip.id)">
                {{ t("action.view") }}
              </button>
              <button class="btn btn-sm" @click.stop="$emit('edit', trip.id)">
                {{ t("action.edit") }}
              </button>
              <button
                v-if="trip.status !== 'cancelled' && trip.status !== 'arrived'"
                class="btn btn-sm btn-danger"
                @click.stop="$emit('cancel', trip.id)"
              >
                {{ t("action.cancel") }}
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// angular/src/app/components/trip-table.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { TripStatusBadgeComponent } from './trip-status-badge.component';
import { TranslatePipe } from '../pipes/translate.pipe';
import { formatCompactDateTime, formatDuration, isNextDay } from '@common/utils/time';
import type { Trip } from '@common/models/trip';

@Component({
  selector: 'app-trip-table',
  standalone: true,
  imports: [CommonModule, RouterLink, TripStatusBadgeComponent, TranslatePipe],
  template: `
    <div class="table-container">
      <table class="table">
        <thead>
          <tr>
            <th>{{ 'table.origin' | t }}</th>
            <th>{{ 'table.destination' | t }}</th>
            <th>{{ 'table.departure' | t }}</th>
            <th>{{ 'table.arrival' | t }}</th>
            <th>{{ 'table.status' | t }}</th>
            <th>{{ 'table.duration' | t }}</th>
            <th>{{ 'table.driver' | t }}</th>
            <th>{{ 'table.actions' | t }}</th>
          </tr>
        </thead>
        <tbody>
          @for (trip of trips; track trip.id) {
            <tr class="table-row-clickable" [routerLink]="['/trips', trip.id]">
              <td>{{ trip.origin }}</td>
              <td>{{ trip.destination }}</td>
              <td class="time-cell">{{ formatCompactDateTime(trip.departureTime, trip.departureTimezone) }}</td>
              <td class="time-cell">
                @if (trip.arrivalTime && trip.arrivalTimezone) {
                  {{ formatCompactDateTime(trip.arrivalTime, trip.arrivalTimezone) }}
                  @if (isNextDay(trip.departureTime, trip.departureTimezone, trip.arrivalTime, trip.arrivalTimezone)) {
                    <span class="next-day">+1</span>
                  }
                } @else {
                  <span class="text-secondary">—</span>
                }
              </td>
              <td><app-trip-status-badge [status]="trip.status" /></td>
              <td class="text-secondary">
                {{ trip.arrivalTime ? formatDuration(trip.departureTime, trip.arrivalTime) : '—' }}
              </td>
              <td>{{ trip.driver }}</td>
              <td>
                <div class="actions">
                  <button
                    class="btn btn-sm"
                    [routerLink]="['/trips', trip.id]"
                    (click)="$event.stopPropagation()"
                  >
                    {{ 'action.view' | t }}
                  </button>
                  <button
                    class="btn btn-sm"
                    [routerLink]="['/trips', trip.id, 'edit']"
                    (click)="$event.stopPropagation()"
                  >
                    {{ 'action.edit' | t }}
                  </button>
                  @if (trip.status !== 'cancelled' && trip.status !== 'arrived') {
                    <button
                      class="btn btn-sm btn-danger"
                      (click)="onCancel(trip.id, $event)"
                    >
                      {{ 'action.cancel' | t }}
                    </button>
                  }
                </div>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  `
})
export class TripTableComponent {
  @Input() trips: Trip[] = [];
  @Output() cancel = new EventEmitter<number>();

  formatCompactDateTime = formatCompactDateTime;
  formatDuration = formatDuration;
  isNextDay = isNextDay;

  onCancel(id: number, event: Event) {
    event.stopPropagation();
    this.cancel.emit(id);
  }
}
