// vue/src/views/TripDetails.vue
<script setup lang="ts">
import { onMounted, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useTripStore } from "@/stores/tripStore";
import { useLocale } from "@/composables/useLocale";
import { useTimezone } from "@/composables/useTimezone";
import { formatCompactDateTime, formatDuration, isNextDay } from "@common/utils/time";
import TripStatusBadge from "@/components/TripStatusBadge.vue";
import TripDetailsSkeleton from "@/components/TripDetailsSkeleton.vue";
import ErrorMessage from "@/components/ErrorMessage.vue";

const route = useRoute();
const router = useRouter();
const store = useTripStore();
const { t } = useLocale();
const { timezone } = useTimezone();

function loadTrip() {
  store.fetchTrip(Number(route.params.id));
}

watch(() => route.params.id, loadTrip);
onMounted(loadTrip);
</script>

<template>
  <div>
    <TripDetailsSkeleton v-if="store.loading" />

    <ErrorMessage
      v-else-if="store.error"
      :message="t('detail.notFound')"
      @retry="loadTrip"
    />

    <template v-else-if="store.currentTrip">
      <div class="flex-between mb-2">
        <h2 class="page-title">{{ t("detail.title") }}</h2>
        <div class="actions">
          <router-link
            :to="{ name: 'trip-edit', params: { id: store.currentTrip.id } }"
            class="btn btn-primary"
          >
            {{ t("action.edit") }}
          </router-link>
          <button class="btn btn-secondary" @click="router.push({ name: 'trips' })">
            {{ t("action.back") }}
          </button>
        </div>
      </div>

      <div class="card">
        <div class="detail-grid">
          <div class="detail-item">
            <label>{{ t("table.origin") }}</label>
            <span>{{ store.currentTrip.origin }}</span>
          </div>
          <div class="detail-item">
            <label>{{ t("table.destination") }}</label>
            <span>{{ store.currentTrip.destination }}</span>
          </div>
          <div class="detail-item">
            <label>{{ t("table.departure") }}</label>
            <span>{{ formatCompactDateTime(store.currentTrip.departureTime, timezone) }}</span>
          </div>
          <div class="detail-item">
            <label>{{ t("table.arrival") }}</label>
            <span v-if="store.currentTrip.arrivalTime">
              {{ formatCompactDateTime(store.currentTrip.arrivalTime, timezone) }}
              <span v-if="isNextDay(store.currentTrip.departureTime, store.currentTrip.departureTimezone, store.currentTrip.arrivalTime, store.currentTrip.arrivalTimezone || '')" class="next-day">+1</span>
            </span>
            <span v-else class="text-secondary">—</span>
          </div>
          <div class="detail-item">
            <label>{{ t("table.status") }}</label>
            <TripStatusBadge :status="store.currentTrip.status" />
          </div>
          <div class="detail-item" v-if="store.currentTrip.arrivalTime">
            <label>{{ t("table.duration") }}</label>
            <span>{{ formatDuration(store.currentTrip.departureTime, store.currentTrip.arrivalTime) }}</span>
          </div>
          <div class="detail-item">
            <label>{{ t("table.driver") }}</label>
            <span>{{ store.currentTrip.driver }}</span>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

// react/src/views/TripDetails.tsx
import { useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { useTripStore } from "@/store/tripStore";
import { useLocale } from "@/hooks/useLocale";
import { useTimezone } from "@/hooks/useTimezone";
import { formatCompactDateTime, formatDuration, isNextDay } from "@common/utils/time";
import TripStatusBadge from "@/components/TripStatusBadge";
import TripDetailsSkeleton from "@/components/TripDetailsSkeleton";
import ErrorMessage from "@/components/ErrorMessage";

export default function TripDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const store = useTripStore();
  const { t } = useLocale();
  const { timezone } = useTimezone();

  const numId = Number(id);
  useEffect(() => { if (numId) store.fetchTrip(numId); }, [id]);

  if (store.loading) return <TripDetailsSkeleton />;
  if (store.error) return <ErrorMessage message={t("detail.notFound")} onRetry={() => store.fetchTrip(numId)} />;
  if (!store.currentTrip) return null;

  const trip = store.currentTrip;

  return (
    <div>
      <div className="flex-between mb-2">
        <h2 className="page-title">{t("detail.title")}</h2>
        <div className="actions">
          <Link to={`/trips/${trip.id}/edit`} className="btn btn-primary">{t("action.edit")}</Link>
          <button className="btn btn-secondary" onClick={() => navigate("/trips")}>{t("action.back")}</button>
        </div>
      </div>

      <div className="card">
        <div className="detail-grid">
          <div className="detail-item">
            <label>{t("table.origin")}</label>
            <span>{trip.origin}</span>
          </div>
          <div className="detail-item">
            <label>{t("table.destination")}</label>
            <span>{trip.destination}</span>
          </div>
          <div className="detail-item">
            <label>{t("table.departure")}</label>
            <span>{formatCompactDateTime(trip.departureTime, timezone)}</span>
          </div>
          <div className="detail-item">
            <label>{t("table.arrival")}</label>
            {trip.arrivalTime ? (
              <span>
                {formatCompactDateTime(trip.arrivalTime, timezone)}
                {isNextDay(trip.departureTime, trip.departureTimezone, trip.arrivalTime, trip.arrivalTimezone || '') && (
                  <span className="next-day">+1</span>
                )}
              </span>
            ) : (
              <span className="text-secondary">—</span>
            )}
          </div>
          <div className="detail-item">
            <label>{t("table.status")}</label>
            <TripStatusBadge status={trip.status} />
          </div>
          {trip.arrivalTime && (
            <div className="detail-item">
              <label>{t("table.duration")}</label>
              <span>{formatDuration(trip.departureTime, trip.arrivalTime)}</span>
            </div>
          )}
          <div className="detail-item">
            <label>{t("table.driver")}</label>
            <span>{trip.driver}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
