// react/src/views/TripDetails.tsx
import { useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { useTripStore } from "@/store/tripStore";
import { useLocale } from "@/hooks/useLocale";
import { formatCompactDateTime, formatDuration, isNextDay } from "@common/utils/time";
import TripStatusBadge from "@/components/TripStatusBadge";
import TripDetailsSkeleton from "@/components/TripDetailsSkeleton";
import ErrorMessage from "@/components/ErrorMessage";

export default function TripDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const store = useTripStore();
  const { t } = useLocale();

  const numId = Number(id);
  useEffect(() => { if (numId) store.fetchTrip(numId); }, [id]);

  if (store.loading) return <TripDetailsSkeleton />;
  if (store.error) return <ErrorMessage message={t("detail.notFound")} onRetry={() => store.fetchTrip(numId)} />;
  if (!store.currentTrip) return null;

  const trip = store.currentTrip;

  return (
    <div>
      <div className="flex-between mb-2">
        <h2 className="page-title">{t("detail.title")}</h2>
        <div className="actions">
          <Link to={`/trips/${trip.id}/edit`} className="btn btn-primary">{t("action.edit")}</Link>
          <button className="btn btn-secondary" onClick={() => navigate("/trips")}>{t("action.back")}</button>
        </div>
      </div>

      <div className="card">
        <div className="detail-grid">
          <div className="detail-item">
            <label>{t("table.origin")}</label>
            <span>{trip.origin}</span>
          </div>
          <div className="detail-item">
            <label>{t("table.destination")}</label>
            <span>{trip.destination}</span>
          </div>
          <div className="detail-item">
            <label>{t("table.departure")}</label>
            <span>{formatCompactDateTime(trip.departureTime, trip.departureTimezone)}</span>
          </div>
          <div className="detail-item">
            <label>{t("table.arrival")}</label>
            {trip.arrivalTime && trip.arrivalTimezone ? (
              <span>
                {formatCompactDateTime(trip.arrivalTime, trip.arrivalTimezone)}
                {isNextDay(trip.departureTime, trip.departureTimezone, trip.arrivalTime, trip.arrivalTimezone) && (
                  <span className="next-day">+1</span>
                )}
              </span>
            ) : (
              <span className="text-secondary">—</span>
            )}
          </div>
          <div className="detail-item">
            <label>{t("table.status")}</label>
            <TripStatusBadge status={trip.status} />
          </div>
          {trip.arrivalTime && (
            <div className="detail-item">
              <label>{t("table.duration")}</label>
              <span>{formatDuration(trip.departureTime, trip.arrivalTime)}</span>
            </div>
          )}
          <div className="detail-item">
            <label>{t("table.driver")}</label>
            <span>{trip.driver}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// angular/src/app/views/trip-details.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { TripService } from '../services/trip.service';
import { I18nService } from '../services/i18n.service';
import { TripStatusBadgeComponent } from '../components/trip-status-badge.component';
import { TripDetailsSkeletonComponent } from '../components/trip-details-skeleton.component';
import { ErrorMessageComponent } from '../components/error-message.component';
import { TranslatePipe } from '../pipes/translate.pipe';
import { formatLocalDateTime, formatDuration } from '@common/utils/time';

@Component({
  selector: 'app-trip-details',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    TripStatusBadgeComponent,
    TripDetailsSkeletonComponent,
    ErrorMessageComponent,
    TranslatePipe
  ],
  template: `
    <div>
      <h2 class="page-title">{{ 'detail.title' | t }}</h2>

      @if (tripService.error()) {
        <app-error-message [message]="tripService.error()!" />
      } @else if (tripService.loading()) {
        <app-trip-details-skeleton />
      } @else if (trip) {
        <div class="card">
          <div class="detail-grid">
            <div class="detail-item">
              <label>{{ 'form.origin' | t }}</label>
              <span>{{ trip.origin }}</span>
            </div>
            <div class="detail-item">
              <label>{{ 'form.destination' | t }}</label>
              <span>{{ trip.destination }}</span>
            </div>
            <div class="detail-item">
              <label>{{ 'form.departureTime' | t }}</label>
              <span>{{ formatLocalDateTime(trip.departureTime, trip.departureTimezone) }}</span>
            </div>
            <div class="detail-item">
              <label>{{ 'form.arrivalTime' | t }}</label>
              <span>
                {{ trip.arrivalTime && trip.arrivalTimezone ? formatLocalDateTime(trip.arrivalTime, trip.arrivalTimezone) : '—' }}
              </span>
            </div>
            <div class="detail-item">
              <label>{{ 'form.status' | t }}</label>
              <app-trip-status-badge [status]="trip.status" />
            </div>
            <div class="detail-item">
              <label>{{ 'table.duration' | t }}</label>
              <span>
                {{ trip.arrivalTime ? formatDuration(trip.departureTime, trip.arrivalTime) : '—' }}
              </span>
            </div>
            <div class="detail-item">
              <label>{{ 'form.driver' | t }}</label>
              <span>{{ trip.driver }}</span>
            </div>
          </div>
        </div>

        <div class="flex gap-1 mt-2">
          <button class="btn btn-primary" [routerLink]="['/trips', trip.id, 'edit']">
            {{ 'action.edit' | t }}
          </button>
          <button
            class="btn btn-danger"
            [disabled]="trip.status === 'cancelled'"
            (click)="handleCancel(trip.id)"
          >
            {{ 'action.cancel' | t }}
          </button>
          <button class="btn btn-secondary" routerLink="/trips">
            {{ 'action.back' | t }}
          </button>
        </div>
      }
    </div>
  `
})
export class TripDetailsComponent implements OnInit {
  formatLocalDateTime = formatLocalDateTime;
  formatDuration = formatDuration;

  get trip() {
    return this.tripService.currentTrip();
  }

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    public tripService: TripService,
    private i18n: I18nService
  ) {}

  ngOnInit() {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (!isNaN(id)) {
      this.tripService.fetchTrip(id);
    }
  }

  async handleCancel(id: number) {
    if (confirm(this.i18n.t('trips.cancelConfirm'))) {
      try {
        await this.tripService.cancelTrip(id);
        this.router.navigate(['/trips']);
      } catch (error) {
        console.error('Failed to cancel trip:', error);
      }
    }
  }
}
