// angular/src/app/components/app-header.component.ts
import { Component } from '@angular/core';
import { LangSelectComponent } from './lang-select.component';
import { TranslatePipe } from '../pipes/translate.pipe';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [LangSelectComponent, TranslatePipe],
  template: `
    <header class="app-header flex-between">
      <h1>
        {{ 'app.title' | t }}
        <span class="framework-badge">Angular</span>
      </h1>
      <app-lang-select />
    </header>
  `
})
export class AppHeaderComponent {}

// react/src/components/AppHeader.tsx
import { useLocale } from "@/hooks/useLocale";
import LangSelect from "./LangSelect";

export default function AppHeader() {
  const { t } = useLocale();
  return (
    <header className="app-header flex-between">
      <h1>
        {t("app.title")}
        <span className="framework-badge">React</span>
      </h1>
      <LangSelect />
    </header>
  );
}
