// vue/src/components/AppHeader.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";
import LangSelect from "@/components/LangSelect.vue";
import TimezoneSelect from "@/components/TimezoneSelect.vue";

const { t } = useLocale();
</script>

<template>
  <header class="app-header flex-between">
    <h1>
      {{ t("app.title") }}
      <span class="framework-badge">Vue</span>
    </h1>
    <div class="flex gap-1">
      <TimezoneSelect />
      <LangSelect />
    </div>
  </header>
</template>

// react/src/components/AppHeader.tsx
import { useLocale } from "@/hooks/useLocale";
import LangSelect from "./LangSelect";
import TimezoneSelect from "./TimezoneSelect";

export default function AppHeader() {
  const { t } = useLocale();
  return (
    <header className="app-header flex-between">
      <h1>
        {t("app.title")}
        <span className="framework-badge">React</span>
      </h1>
      <div className="flex gap-1">
        <TimezoneSelect />
        <LangSelect />
      </div>
    </header>
  );
}
