// vue/src/components/ErrorMessage.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";

defineProps<{ message: string }>();
defineEmits<{ retry: [] }>();

const { t } = useLocale();
</script>

<template>
  <div class="error">
    <p>{{ message }}</p>
    <button class="btn btn-primary mt-2" @click="$emit('retry')">
      {{ t("trips.retry") }}
    </button>
  </div>
</template>

// react/src/components/ErrorMessage.tsx
import { useLocale } from "@/hooks/useLocale";

interface Props {
  message: string;
  onRetry?: () => void;
}

export default function ErrorMessage({ message, onRetry }: Props) {
  const { t } = useLocale();
  return (
    <div className="error">
      <p>{message}</p>
      {onRetry && (
        <button className="btn btn-primary mt-2" onClick={onRetry}>
          {t("trips.retry")}
        </button>
      )}
    </div>
  );
}
