// vue/src/components/ErrorMessage.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";

defineProps<{ message: string }>();
defineEmits<{ retry: [] }>();

const { t } = useLocale();
</script>

<template>
  <div class="error">
    <p>{{ message }}</p>
    <button class="btn btn-primary mt-2" @click="$emit('retry')">
      {{ t("trips.retry") }}
    </button>
  </div>
</template>

// react/src/components/ErrorMessage.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useLocale } from "@/hooks/useLocale";
export default function ErrorMessage({ message, onRetry }) {
    const { t } = useLocale();
    return (_jsxs("div", { className: "error", children: [_jsx("p", { children: message }), onRetry && (_jsx("button", { className: "btn btn-primary mt-2", onClick: onRetry, children: t("trips.retry") }))] }));
}
