// vue/src/components/TimezoneSelect.vue
<script setup lang="ts">
import { useTimezone } from "@/composables/useTimezone";
import CustomSelect from "./CustomSelect.vue";

const { timezone, timezoneOptions, setTimezone } = useTimezone();
</script>

<template>
  <CustomSelect
    :modelValue="timezone"
    :options="timezoneOptions"
    class="timezone-select"
    @update:modelValue="setTimezone($event)"
  >
    <template #trigger="{ option }">🌍 {{ option?.label }}</template>
    <template #option="{ option }">{{ option.label }}</template>
  </CustomSelect>
</template>

// react/src/components/TimezoneSelect.tsx
import { useTimezone } from "@/hooks/useTimezone";
import CustomSelect from "./CustomSelect";

export default function TimezoneSelect() {
  const { timezone, timezoneOptions, setTimezone } = useTimezone();
  return (
    <CustomSelect
      value={timezone}
      options={timezoneOptions}
      className="timezone-select"
      renderTrigger={opt => `🌍 ${opt?.label ?? ""}`}
      renderOption={opt => opt?.label ?? ""}
      onChange={setTimezone}
    />
  );
}
