// vue/src/components/TripStatusBadge.vue
<script setup lang="ts">
import { useLocale } from "@/composables/useLocale";
import type { TripStatus } from "@common/models/trip";

defineProps<{ status: TripStatus }>();

const { t } = useLocale();
</script>

<template>
  <span class="badge" :class="`badge-${status}`">
    {{ t(`status.${status}`) }}
  </span>
</template>

// react/src/components/TripStatusBadge.tsx
import { useLocale } from "@/hooks/useLocale";
import type { TripStatus } from "@common/models/trip";

export default function TripStatusBadge({ status }: { status: TripStatus }) {
  const { t } = useLocale();
  return <span className={`badge badge-${status}`} role="status" aria-label={t(`status.${status}`)}>{t(`status.${status}`)}</span>;
}
