// vue/src/components/TripFormSkeleton.vue
<template>
  <div class="card">
    <div v-for="row in 3" :key="row" class="form-row">
      <div v-for="col in 2" :key="col" class="form-group">
        <div class="skeleton skeleton-text" style="width: 90px; height: 13px; margin-bottom: 8px;"></div>
        <div class="skeleton skeleton-text" style="height: 38px; border-radius: 6px;"></div>
      </div>
    </div>
    <div class="form-group">
      <div class="skeleton skeleton-text" style="width: 60px; height: 13px; margin-bottom: 8px;"></div>
      <div class="skeleton skeleton-text" style="height: 38px; border-radius: 6px;"></div>
    </div>
    <div class="flex gap-1 mt-3">
      <div class="skeleton skeleton-text" style="width: 80px; height: 36px; border-radius: 6px;"></div>
      <div class="skeleton skeleton-text" style="width: 80px; height: 36px; border-radius: 6px;"></div>
    </div>
  </div>
</template>

// react/src/components/TripFormSkeleton.tsx
export default function TripFormSkeleton() {
  return (
    <div className="card">
      {[0, 1, 2].map(row => (
        <div className="form-row" key={row}>
          {[0, 1].map(col => (
            <div className="form-group" key={col}>
              <div className="skeleton skeleton-text" style={{ width: 90, height: 13, marginBottom: 8 }} />
              <div className="skeleton skeleton-text" style={{ height: 38, borderRadius: 6 }} />
            </div>
          ))}
        </div>
      ))}
      <div className="form-group">
        <div className="skeleton skeleton-text" style={{ width: 60, height: 13, marginBottom: 8 }} />
        <div className="skeleton skeleton-text" style={{ height: 38, borderRadius: 6 }} />
      </div>
      <div className="flex gap-1 mt-3">
        <div className="skeleton skeleton-text" style={{ width: 80, height: 36, borderRadius: 6 }} />
        <div className="skeleton skeleton-text" style={{ width: 80, height: 36, borderRadius: 6 }} />
      </div>
    </div>
  );
}
